### ISSUE TITLE
missing license field in package.json

### ISSUE THREAD

**Issue by DanielRuf** [sulu/SuluHeadlessBundle#128]
Currently https://github.com/sulu/SuluHeadlessBundle/blob/0.x/Resources/js-website/package.json has no license defined and no extra `LICENSE` file.

This produces the following output when we run [licensee](https://www.npmjs.com/package/licensee) with `corrections: true`:

```yaml
sulu-headless-bundle@0.0.0
  NOT APPROVED
  Terms: Invalid license metadata
  Repository: None listed
  Homepage: None listed
  Author: None listed
  Contributors: None listed
```
