### ISSUE TITLE
Varnish Cache Refresh Triggering HTML Requests Instead of JSON (HTTP 406)

### ISSUE THREAD

**Issue by qguillou-niji** [sulu/SuluHeadlessBundle#146]
I'm using this bundle on my Sulu project, which has a Varnish cache configured.

When a page is modified, the cache invalidation is performed automatically, but I also see a cache refresh being performed on the current page and its child pages via GET requests on the page URLs.
These GET calls are made without the ".json" suffix at the end of the URL, so Sulu tries to respond with the HTML format, which is not supported by my Sulu project. This results in an HTTP 406 error response, which in turn leads to error logs.

Nothing impactful, everything seems to work correctly, but I'm wondering if there's a configuration that could address this error? (Prevent cache refresh, make the call in JSON format, or other options).

Thank you in advance for your feedback.

**Comment by alexander-schranz** [comment]
@qguillou-niji If you are using varnish you should also enable tag based caches. Sulu purges the URL + a Tag referencing the page - this tag is written on all URL which did use that page for rendering. Sulu have tag based caching enabled by default also for the php based http cache. For varnish you need also enable it I think it is this documentation: https://docs.sulu.io/en/2.6/cookbook/caching-with-varnish.html#using-xkey /cc @wachterjohannes

**Comment by qguillou-niji** [comment]
Thank you for your response @alexander-schranz .
I have followed the required configuration in the link you sent, including:
- commenting out the lines in public/index.php,
- the Varnish configuration,
- the Sulu HTTP cache configuration as you can find below.

```
sulu_http_cache:
    tags:
        enabled: true
    cache:
        max_age: 86400
        shared_max_age: 86400
    proxy_client:
        symfony:
            enabled: false # disable this when varnish is used
        varnish:
            enabled: true
            servers:
                - '%env(resolve:VARNISH_URL)%'
            tag_mode: purgekeys
```
